### ISSUE TITLE
Python 3: Error

### ISSUE THREAD

**Issue by mykaleelurrahman** [egaus/MaliciousMacroBot#15]
WARNING:root:Could not load model from pickle file /usr/local/lib/python3.4/dist-packages/mmbot/model/modeldata.pickle.
Failed with error: EOF: reading array data, expected 262144 bytes got 208786
ERROR:root:Error loading model /usr/local/lib/python3.4/dist-packages/mmbot/model/modeldata.pickle
Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/mmbot/mmbot.py", line 700, in mmb_init_model
    newdoc_cnt = self.load_model_data(exclude)
  File "/usr/local/lib/python3.4/dist-packages/mmbot/mmbot.py", line 310, in load_model_data
    maldocs = self.get_samples_from_disk(self.malicious_path)
AttributeError: 'MaliciousMacroBot' object has no attribute 'malicious_path'

**Comment by wroersma** [comment]
Did you do a pip install for mmbot or pull from the git repo? Can you do a md5sum on that /usr/local/lib/python3.4/dist-packages/mmbot/model/modeldata.pickle file? It should be 6e56e271f0a6fda1d2a97d4c5e5d2baa.

**Comment by mykaleelurrahman** [comment]
I did pip install for mmbot. The hash is different for me!

**Comment by wroersma** [comment]
I will update a copy of it and create a pull request and you can grab it from there.

**Comment by wroersma** [comment]
Here is a link if you want to grab it manually https://drive.google.com/open?id=1OIjBrE2Z4ywiKOV82PBf3gD4AVQh5ZF6. I will get a code fix for this up shortly as well but just in case you need the file.

**Comment by wroersma** [comment]
So if you got and pull from here https://github.com/wroersma/MaliciousMacroBot/tree/dev you should be able to pip uninstall mmbot and then clone that to a dir and install it from there. It should get merged upstream shortly so it's possible you could wait until then. Please let me know if you have any other questions.

**Comment by egaus** [comment]
Hi @mykaleelurrahman, couple of questions:
 - Can you provide the lines of code that led to that error with the full output?
 - Also, please run this: "pip freeze | grep mmbot" so we can confirm the version.  
 - What OS are you running on?  I've been building and testing primarily on Linux and confirming tests pass on a Mac.  I just ran a fresh set of tests on v1.0.10 from PyPI as well as the updates @wroersma  and I just added to this repo and it works for me on python 2.7 and 3.5.

**Comment by wroersma** [comment]
Any update on this issue @mykaleelurrahman ?

**Comment by mykaleelurrahman** [comment]
Hey @wroersma ,
It works now! Thanks. Please add ujson to the setup installation.
On fresh install it is missing ujson module.

**Comment by egaus** [comment]
Glad its working for you @mykaleelurrahman.  Thanks.  I'll make sure ujson is added to the setup installation.
