### ISSUE TITLE
Can you share your dataset?

### ISSUE THREAD

**Issue by shelovemee** [egaus/MaliciousMacroBot#18]
Hi egaus, thanks for your great work. 

I'm an independent malware researcher. I'm interested in malicious documents detection, but i don't have enough malware samples. Can you share your dataset to me? If you can't, can you tell me where did you obtain so large malware corpus(30000 malicious documents and 10000 benign documents)? Thanks

**Comment by egaus** [comment]
Hi shelovemee.  The data set was primarily obtained from a paid VirusTotal service, so unfortunately I can't provide the whole data set to others.  You may also want to checkout Hybrid-Analysis and Joe's Sandbox.

**Comment by shelovemee** [comment]
Hi egaus. Thanks for your help. I will checkout Hybrid-Analysis and Joe's Sandbox.
