### ISSUE TITLE
[Info] MMBot test script

### ISSUE THREAD

**Issue by dhondta** [egaus/MaliciousMacroBot#23]
For what it's worth, if you're interested, I made a test script relying on your library at [https://github.com/dhondta/malicious-macro-tester](https://github.com/dhondta/malicious-macro-tester).
It allows to complement the prediction with the detection rate from VirusTotal and to produce a report in various different output formats (Markdown, HTML, XML, JSON, PDF).

**Comment by wroersma** [comment]
We are very interested in making this a function that's available in mmbot would you be willing to work with us to get it added?

**Comment by dhondta** [comment]
Hi,
I can help you in function of your requirements and my available time.
What feature would you like to get added exactly ?
